export const salesforce_technologies = [
    { value: 'salesforce_platform', label: 'Salesforce Platform' },
    { value: 'sales_cloud', label: 'Sales Cloud' },
    { value: 'service_cloud', label: 'Service Cloud' },
    { value: 'experience_cloud', label: 'Experience Cloud' },
    { value: 'marketing_cloud', label: 'Marketing Cloud' },
    { value: 'b2b_commerce_cloud', label: 'B2B Commerce Cloud' },
    { value: 'b2c_commerce_cloud', label: 'B2C Commerce Cloud' },
    { value: 'cpq', label: 'CPQ' },
];

export const industries = [
    { value: 'Agriculture', label: 'Agriculture' },
    { value: 'Automotive', label: 'Automotive' },
    { value: 'Banking', label: 'Banking' },
    { value: 'Biotechnology', label: 'Biotechnology' },
    { value: 'Chemicals', label: 'Chemicals' },
    { value: 'Communications', label: 'Communications' },
    { value: 'Construction', label: 'Construction' },
    { value: 'Consulting', label: 'Consulting' },
    { value: 'Consumer Packaged Goods', label: 'Consumer Packaged Goods' },
    { value: 'Education', label: 'Education' },
    { value: 'Energy', label: 'Energy' },
    { value: 'Engineering', label: 'Engineering' },
    { value: 'Entertainment', label: 'Entertainment' },
    { value: 'Environmental', label: 'Environmental' },
    { value: 'Financial Services', label: 'Financial Services' },
    { value: 'Food & beverage', label: 'Food & Beverage' },
    { value: 'Government', label: 'Government' },
    { value: 'Healthcare', label: 'Healthcare' },
    { value: 'High Tech', label: 'High Tech' },
    { value: 'Hospitality', label: 'Hospitality' },
    { value: 'Insurance', label: 'Insurance' },
    { value: 'Manufacturing', label: 'Manufacturing' },
    { value: 'Media', label: 'Media' },
    { value: 'Nonprofit', label: 'Nonprofit' },
    { value: 'Other', label: 'Other' },
    { value: 'Pharmaceuticals', label: 'Pharmaceuticals' },
    { value: 'Real Estate', label: 'Real Estate' },
    { value: 'Recreation', label: 'Recreation' },
    { value: 'Retail', label: 'Retail' },
    { value: 'Shipping', label: 'Shipping' },
    { value: 'Technology', label: 'Technology' },
    { value: 'Telecommunications', label: 'Telecommunications' },
    { value: 'Transportation', label: 'Transportation' },
    { value: 'Utilities', label: 'Utilities' }
];

export const filterby = [
    "Admin",
    "Developer", 
    "Consultant", 
    "Architect",
    "Marketing",
    "Commerce",
    "Industry Cloud",
    "Designer",
    "CRM Analytics", 
    "Heroku",
    "Mulesoft"
];

export const skillsDetails = [
    { id: "a0lIo000000viJPIAY", text: 'Salesforce', imageSrc: '/Salesforce.png', bgColor: 'bg-blue-100', checkedColor: 'bg-blue-500', borderColor: 'border-blue-600', textColor: 'text-blue-400' },
    { id: "a0lIo000000viJQIAY", text: 'Mulesoft', imageSrc: '/Mulesoft.png', bgColor: 'bg-blue-100', checkedColor: 'bg-blue-500', borderColor: 'border-blue-600', textColor: 'text-blue-400' },
    { id: "a0lIo000000viJSIAY", text: 'Heroku', imageSrc: '/heroku.png', bgColor: 'bg-purple-100', checkedColor: 'bg-purple-500', borderColor: 'border-purple-600', textColor: 'text-purple-900' },
    { id: "a0lIo000000viJTIAY", text: 'Sales Cloud', imageSrc: '/sales-cloud.svg', bgColor: 'bg-green-100', checkedColor: 'bg-green-500', borderColor: 'border-green-600', textColor: 'text-green-800' },
    { id: "a0lIo000000viJUIAY", text: 'Service Cloud', imageSrc: '/service-cloud.svg', bgColor: 'bg-pink-100', checkedColor: 'bg-pink-500', borderColor: 'border-pink-600', textColor: 'text-pink-600' },
    { id: "a0lIo000000viJVIAY", text: 'Marketing Cloud', imageSrc: '/marketing-cloud.svg', bgColor: 'bg-orange-100', checkedColor: 'bg-orange-500', borderColor: 'border-orange-600', textColor: 'text-orange-400' },
    { id: "a0lIo000000viJWIAY", text: 'B2B Commerce Cloud', imageSrc: '/commerce-cloud.svg', bgColor: 'bg-green-100', checkedColor: 'bg-green-500', borderColor: 'border-green-600', textColor: 'text-green-800' },
    { id: "a0lIo000000viJXIAY", text: 'B2C Commerce Cloud', imageSrc: '/commerce-cloud.svg', bgColor: 'bg-green-100', checkedColor: 'bg-green-500', borderColor: 'border-green-600', textColor: 'text-green-800' },
    { id: "a0lIo000000viJaIAI", text: 'Experience Cloud', imageSrc: '/Salesforce.png', bgColor: 'bg-blue-100', checkedColor: 'bg-blue-500', borderColor: 'border-blue-600', textColor: 'text-blue-400' },
    { id: "a0lIo000000viJRIAY", text: 'Industry Cloud', imageSrc: '/Salesforce.png', bgColor: 'bg-blue-100', checkedColor: 'bg-blue-500', borderColor: 'border-blue-600', textColor: 'text-blue-400' },
    { id: "a0lIo000000viJZIAY", text: 'Einstein Copilot', imageSrc: '/encop.webp', bgColor: 'bg-purple-100', checkedColor: 'bg-purple-500', borderColor: 'border-purple-600', textColor: 'text-purple-900' },
    { id: "a0lIo000000viJYIAY", text: 'AI', imageSrc: '/encop.webp', bgColor: 'bg-purple-100', checkedColor: 'bg-purple-500', borderColor: 'border-purple-600', textColor: 'text-purple-900' },
];

